<?php

/**
 * @file
 * Contains browser_push_notification.module functionality.
 */

/**
 * Implements hook_page_attachments().
 */
function browser_push_notification_page_attachments(&$page) {
  $page['#attached']['html_head_link'][][] = [
    'rel' => 'manifest',
    'href' => '/manifest.json',
  ];
}

/**
 * Implements hook_page_attachments_alter() for loaing libraries.
 * Load service-worker only in home page,base url or in login page.
 */

function browser_push_notification_page_attachments_alter(array &$build) {
  global $base_url;
  $login_url = $base_url. '/user/login';
  $is_front = NULL;
  $current_path = rtrim($base_url.\Drupal::service('path.current')->getPath(),'/');
  if ($login_url == $current_path || $base_url == $current_path || $is_front = \Drupal::service('path.matcher')->isFrontPage()) { 
    $build['#attached']['library'][] = 'browser_push_notification/service-worker';
  }
}
